spring:
  datasource:
    url: jdbc:postgresql://order-db:5432/order_db
    username: postgres
    password: Ankit@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:29092




server:
  port: 8082